### PR TITLE
Add flashPixel and Animations

### PR DESCRIPTION
**Pull request by chriskinsman**
- add flashPixel
- add showInitialAnimation
- add showFinalAnimation
- update examples
- update docs

### CODE REVIEW

**Comment by chriskinsman** [comment]
Happy to merge myself @globalroo but don't want to overstep my bounds.

Thanks!

**Review by globalroo — APPROVED** [review]
Happy for you to merge. I'll adjust collaborators on npm too if you'd like to publish. 👍

**Comment by chriskinsman** [comment]
Sure. Sounds good

**Comment by chriskinsman** [comment]
@globalroo if you could add chriskinsman on npmjs I will publish this and a fix I just merged.

Thanks!

**Pull request merged**
